name: listit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  flutter_form_builder: ^9.3.0
  get_storage: ^2.1.1


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2

flutter: 
  uses-material-design: true

